### ISSUE TITLE
Think this could be used with a getchip/pocketchip

### ISSUE THREAD

**Issue by yratof** [javl/linger#1]
Looking at this project, I thought it would be a great little weekend task for myself, but I don't have an adaprter for the pizero to get the wifi attached, so I'm thinking is there a way of doing it without the additional USB device.

Could this be done with the getchip / pocketchip?

**Comment by javl** [comment]
I used separate devices because when I was using a single device the messages I was sending out would be received at the same time, but somehow in a corrupt form.
Using a dedicated sending and receiving device fixed this, and might actually be a bit faster as well because it doesn't have to device its time between the two actions. 

-----

**Update:** It also allows you to spend more time listening for probe requests, increasing the chances of recording them, as you might miss one when broadcasting yourself. This could of course be solved by having something like a training mode, so you first only capture devices for a couple of days and then stop listening and only broadcast.

-----

According to [this thread](https://bbs.nextthing.co/t/pocketchip-monitor-mode-on-internal-wifi-probe-requests-working/5509) on the pocketchip forum, the wifi module is able to go into monitor mode so it could work. I'd like to try it, but unfortunately I don't own a CHIP.

Most of the scripts accept a couple of arguments, like what device to use, so you should be able to run both the transmit and receive scripts on the same `mon0` device.

Though not really an issue, I'm keeping this open for any questions as it would indeed be a nice device to run Linger on.

**Comment by javl** [comment]
Thanks, now I want to get a PocketCHIP ;)

**Comment by yratof** [comment]
haha, thanks for getting back on me there – I must admit, it's a pretty cool device. Kind of feels like when the world ends, this is whats going to remain to put a network back together for international communications.

But start with a chip, it's only $9! 

![img_3567](https://cloud.githubusercontent.com/assets/1001935/26063379/2ac5666c-398e-11e7-9b5b-c52c5560354d.JPG)
